version: '3.8'

services:
  app:
    build: .
    container_name: expensemanager-app
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  redis:
    image: redis:7-alpine
    container_name: expensemanager-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5