
spring.datasource.url=jdbc:postgresql://dpg-d3aiup24d50c73dbcm40-a.singapore-postgres.render.com/expensemanager_o7zm
spring.datasource.username=expensemanager_o7zm_user
spring.datasource.password=6n4BLYXy6J6AQI3ZuAv5y1meAawFYSul