spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}
server.servlet.context-path=/api/v1.0
jwt.secret=${JWT_SECRET}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

app.activation.url=${BACKEND_BASE_URL}
money.manager.frontend.url=${FRONTEND_BASE_URL}
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
sendgrid.api.key=${SENDGRID_API_KEY}
spring.mail.from=rishabhm4343@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=17324
spring.data.redis.password=${REDIS_PASSWORD}